#+title: Operator closure estimates for BNV nucleon decays

Our code contains the Mathematica code that implements our symbolic rewriting
system as well as the Python code in which we perform much of our analysis.

* Rewriting system

Load up the definitions in the core files:
#+begin_src wolfram
Get["main.m"];
Get["operators.m"];
Get["rules.m"];
Get["decay.m"];
Get["pmatch.m"];
Get["symmetries.m"];
#+end_src

The main function of the package is =MatchingData=, which is a wrapper around a
number of auxiliary functions. =MatchingData= returns the matching estimates
associated with a specific field-string operator. Its inputs are the operator
label, provided as a string, and the flavour indices, a list of integers. For example
#+begin_src wolfram
MatchingData["11", {1, 1, 1, 1}]
#+end_src
The output is in the mass basis.

* Matching-estimate database

Our results can be accessed through the =Pandas= dataframes we provide in
=database.py=. We provide an example notebook showing how to access these data
in the =examples/= directory.
