#+title: Operator closure estimates

Run the definitions in the core files:
#+begin_src wolfram
Get["main.m"];
Get["operators.m"];
Get["rules.m"];
Get["decay.m"];
#+end_src

The main function of the package is =MatchingData=, which is a wrapper around a
number of auxiliary functions. =MatchingData= returns the raw matching data
in the interaction basis.

A number of steps have been wrapped into a convenient helper function:
#+begin_src wolfram
WriteMatchingData["9", {1,1,1,2}, NotebookDirectory[] <> "data/"]
#+end_src
which writes out the matching data with the flavour indices ={1,1,1,2}=.

The function =NucleonDecays= returns a replacement rule mapping the nucleon
decay process name to the corresponding expression.
#+begin_src wolfram
NucleonDecays["9", {1,1,1,2}, "Symbolic"]
#+end_src
The argument ="Numeric"= can also be passed in. This function calculates the
matching from scratch. If it has already been written out to a data file, this
can be used instead with
#+begin_src wolfram
NucleonDecaysWithMatchingData["9", ReadList["data/op9_1112.dat"], "Symbolic"]
#+end_src

This is all tied into the function =ExtractDominantMatchingByOperator=, which
returns a list of the dominant contributions to each LEFT operator that
contribute to nucleon decay
#+begin_src wolfram
ExtractDominantMatchingByOperator[ReadList["data/op9_1112.dat"]]
#+end_src
